theme: jekyll-theme-minimal
linkedin_profile: https://www.linkedin.com/in/nándor-kiss-722aa26a/
email: kipal42@gmail.com
error_mode: strict
sections:
  - link: education
    name: Education

  - link: work
    name: Work Experiences

  - link: professional
    name: Professional Interest

  - link: personal
    name: Personal Interest
