---
email: kipal42@gmail.com
linkedin_profile: "https://www.linkedin.com/in/nándor-kiss-722aa26a/"
sections:
  -
    link: education
    name: Education
  -
    link: work
    name: "Work Experiences"
  -
    link: professional
    name: "Professional Interests"
  -
    link: personal
    name: "Personal Interests"
theme: jekyll-theme-minimal
